name: "CI Tests"

on:
    pull_request:
    push:

jobs:
    tests:
        name: PHPUnit Tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                - deps: low
                  php: 5.6
                  symfony: 3.4
                - deps: normal
                  php: 7.2
                  symfony: 4.4
                - deps: normal
                  php: 7.3
                  symfony: 5.1
                - deps: normal
                  php: 7.4
                  symfony: 5.2
                - deps: normal
                  php: 8.0
                  symfony: 5.x-dev

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"
              with:
                  fetch-depth: 2

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php: "${{ matrix.php }}"

            - name: "Cache composer packages"
              uses: "actions/cache@v2"
              with:
                  path: "~/.composer/cache"
                  key: "php-${{ matrix.php }}-composer-locked-${{ hashFiles('composer.lock') }}"
                  restore-keys: "php-${{ matrix.php }}-composer-locked-"

            - name: "Install Symfony"
              run: "composer require symfony/symfony:${{ matrix.symfony }} --no-update"

            - name: "Install dependencies with composer"
              run: "composer update --no-interaction --prefer-stable"
              if: "${{ matrix.deps == 'normal' }}"

            - name: "Install lowest possible dependencies with composer"
              run: "composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest"
              if: "${{ matrix.deps == 'low' }} "

            - name: "Run PHPUnit"
              run: "composer test"
